# Generated by Django 4.1.1 on 2022-10-07 16:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_siteuser_problemswrong'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='level',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='user',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='wattval',
        ),
        migrations.RemoveField(
            model_name='siteuser',
            name='isproblemsetter',
        ),
        migrations.RemoveField(
            model_name='siteuser',
            name='problems1attempt',
        ),
        migrations.RemoveField(
            model_name='siteuser',
            name='problemswrong',
        ),
        migrations.AddField(
            model_name='problem',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 7, 16, 38, 16, 18896, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
