# Generated by Django 4.1.1 on 2022-10-07 19:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_remove_problem_category_remove_problem_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='release',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
